#!/bin/sh
k=0
rbdmounts=$(df | awk '{if ($1~"/dev/rbd.*") printf $6" "}')
while [ -n "${rbdmounts}" ] && [ $k -lt 10 ]
do
/usr/bin/umount ${rbdmounts}
rbdmounts=$(df | awk '{if ($1~"/dev/rbd.*") printf $6" "}')
k=$(($k+1))
done
/usr/bin/rbdmap unmap-all
